version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./apps/backend/uploads:/app/apps/backend/uploads